# Generated by Django 2.1.1 on 2019-02-22 23:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
        ('skill', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='address', max_length=511, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='user',
            name='ended',
            field=models.DateField(default=datetime.date.today, verbose_name='Ended at'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=True, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='nationality', max_length=255, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+999999999', max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 17 digits allowed.", regex='^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\\s\\./0-9]*$')], verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sector.Sector', verbose_name='Work sector'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(to='skill.Skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='started',
            field=models.DateField(default=datetime.date.today, verbose_name='Started at'),
        ),
    ]
