# Generated by Django 2.1.1 on 2019-02-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190224_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
